apiVersion: v1
kind: Service
metadata:
  name: superset
  labels:
    app: superset
spec:
  ports:
  - name: http
    port: 8088
    targetPort: 8088
  selector:
    app: superset
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: superset-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: gke-cluster-1-default-pool-8b890037-6tcb
        - name: REDIS_HOST
          value: gke-cluster-1-default-pool-8b890037-6tcb
	- name: POSTGRES_USER
          value: admin	
	- name: POSTGRES_PASSWORD
          value: admin 
        - name: DB_NAME
          value: superset
        - name: PYTHONPATH
          value: "${PYTHONPATH}:/home/superset/superset/"  
        image: amancevice/superset:latest
        name: superset
        ports:
        - containerPort: 8088
        volumeMounts:
        - mountPath: /home/superset/superset
          name: superset-config
      volumes:
      - name: superset-config
        configMap:
          name: superset-config
